---
name: Create Specification Document

on:
  workflow_dispatch:
    inputs:
      revision_mark:
        description: 'Set revision mark as Development, Stable, Frozen, or Ratified:'
        required: true
        type: choice
        options:
          - Development
          - Stable
          - Frozen
          - Ratified
        default: Development
      prerelease:
        description: Tag as a pre-release?
        required: false
        type: boolean
        default: true
      draft:
        description: Create release as a draft?
        required: false
        type: boolean
        default: false

  pull_request:

  push:
    branches:
      - main

permissions:
  contents: write  # Required for gh-pages deployment and creating releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get next version
        uses: reecetech/version-increment@2024.4.4
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Pull Container
        run: docker pull riscvintl/riscv-docs-base-container-image:latest

      - name: Update environment variables
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "VERSION=v${{ steps.version.outputs.version }}" >> "$GITHUB_ENV"
          echo "REVMARK=${{ github.event.inputs.revision_mark }}" >> "$GITHUB_ENV"

      - name: Build Files
        run: make

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: |
            ${{ github.workspace }}/build/*.pdf
            ${{ github.workspace }}/build/*.html
          retention-days: 30

      - name: Create Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/build/*.pdf
            ${{ github.workspace }}/build/*.html
          tag_name: v${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GHTOKEN }}
          publish_dir: ${{ github.workspace }}/build
